name: Shaping Bad Test Workflow

on:
  push:
    branches: [ master ]

jobs:
  unit_test_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get our files
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      # Put actual test steps starting from here!
